// Negative Rares generated by Wraith in antes WNR_FIRST_ANTE-WNR_LAST_ANTE,
// weighted the same way as early_negative_rares:
//
//   score = sum over each qualifying ante's Wraith negative of (a weight that
//   is flat at WNR_WEIGHT_BASE through WNR_TAPER_ANTE - 1 and tapers off from
//   there -- see wnr_weight below, copied verbatim from early_negative_rares
//   so the two stay comparable). The weight only ever decreases, so once it
//   reaches zero every later ante is skipped entirely (wnr_effective_last_ante).
//
// Unlike early_negative_rares, the source of the Rare is not the shop: Wraith
// always creates a Rare joker (next_joker_rarity hard-codes Rarity_Rare for
// S_Wraith, no roll involved), and Wraith cards only exist in a run once
// Sixth Sense or Seance has actually turned a played hand into one. So each
// ante is gated in two steps:
//
//   1. Would Sixth Sense or Seance produce a Wraith within its first
//      WNR_TRIGGERS spectral creations THIS ante? (a hand of a single 6 for
//      Sixth Sense, a Straight Flush for Seance -- "trigger" means one such
//      hand, one spectral card created). This is a hypothetical check, same
//      as early_negative_rares not caring whether the shop it scans was ever
//      actually visited: no shop/pack scan for owning either joker is done.
//   2. If so, the ante's Wraith queue (S_Wraith) is read WNR_WRAITH_DEPTH
//      draws deep, and every Negative edition found there adds the ante's
//      weight to the score.
//
// -D WNR_COUNT_ONLY returns the plain count of Wraith negatives instead of
// the weighted total, for checking the weighting against another filter.
//
// Cost-cutting, all exact:
//  * Step 1 never draws a joker identity: it only asks "is this spectral a
//    Wraith", so next_spectral is called directly and nothing about the
//    spectral pool's locks needs setting up (The_Soul / Black_Hole are RETRY
//    entries in SPECTRALS and RETRY is always locked, so they are skipped by
//    randchoice_common's own resample loop with no help from this filter).
//  * Step 1 short-circuits: Seance's triggers are never drawn once Sixth
//    Sense's have already found a Wraith this ante (the OR below), and the
//    inner loop returns as soon as one trigger is a Wraith.
//  * Step 2 never draws a joker identity either: rarity is hard-coded for
//    S_Wraith (no roll) and edition lives on its own node (R_Joker_Edition),
//    independent of the identity node (R_Joker_Rare), so reading only the
//    edition is exact -- nothing this filter skips is read by anything it
//    does read.

// Build options (pass with --build_opts "-D NAME" or "-D NAME=VALUE"):
// @opt WNR_FIRST_ANTE=1  first ante checked for Wraith negatives
// @opt WNR_LAST_ANTE=15  last ante checked for Wraith negatives
// @opt WNR_WEIGHT_BASE=20  score of a Wraith negative before the taper starts
// @opt WNR_TAPER_ANTE=10  ante the weight starts tapering at
// @opt WNR_TAPER_RATE=0.2  fraction of WNR_WEIGHT_BASE the weight loses per ante from the taper on
// @opt WNR_TRIGGERS=3  Sixth Sense / Seance spectral creations per ante checked for a Wraith
// @opt WNR_WRAITH_DEPTH=3  Wraith-created jokers per ante checked for Negative
// @opt WNR_COUNT_ONLY  score the plain count of Wraith negatives instead of the weighted total

#define INSTANCE_NO_DECK
#include "lib/immolate.cl"

#ifndef WNR_FIRST_ANTE
#define WNR_FIRST_ANTE 1
#endif
#ifndef WNR_LAST_ANTE
#define WNR_LAST_ANTE 15
#endif
// A Wraith negative in ante A scores this, tapering the same way
// early_negative_rares' weight does; kept identical so the two are
// comparable at the same ante.
#ifndef WNR_WEIGHT_BASE
#define WNR_WEIGHT_BASE 20
#endif
// The ante the taper starts at, and the fraction of WNR_WEIGHT_BASE it
// removes per ante from there on -- the two magic numbers of the weight
// formula, named so the cutoff below can be derived from them instead of
// hard-coded.
#ifndef WNR_TAPER_ANTE
#define WNR_TAPER_ANTE 10
#endif
#ifndef WNR_TAPER_RATE
#define WNR_TAPER_RATE 0.2
#endif
// How many of Sixth Sense's / Seance's spectral creations, per ante, are
// checked for a Wraith.
#ifndef WNR_TRIGGERS
#define WNR_TRIGGERS 3
#endif
// How many of the ante's Wraith-created jokers are checked for Negative,
// once a Wraith is confirmed reachable that ante.
#ifndef WNR_WRAITH_DEPTH
#define WNR_WRAITH_DEPTH 3
#endif

// The weight an ante's negative is worth: flat at WNR_WEIGHT_BASE through
// WNR_TAPER_ANTE - 1, then reduced by WNR_TAPER_RATE * WNR_WEIGHT_BASE per
// ante from WNR_TAPER_ANTE on. Copied verbatim from early_negative_rares.
inline int wnr_weight(int ante) {
    int weight = WNR_WEIGHT_BASE;
    if (ante >= WNR_TAPER_ANTE) {
        weight -= ante * WNR_WEIGHT_BASE * WNR_TAPER_RATE;
    }
    return weight;
}

// The formula above only ever decreases as ante grows, so once it reaches
// zero or below every later ante is worthless too -- there is no point
// gating Sixth Sense/Seance/Wraith draws for an ante that cannot add
// anything to the score. Rather than hard-code that ante, walk forward from
// WNR_FIRST_ANTE (cheap: no RNG, just the arithmetic above) and stop at the
// last one still worth something, capped at `lastAnte`. Recomputing this
// from WNR_WEIGHT_BASE/WNR_TAPER_ANTE/WNR_TAPER_RATE means changing any of
// them keeps the loop bound honest instead of silently doing dead work (or
// silently stopping early).
inline int wnr_effective_last_ante(int lastAnte) {
    for (int ante = WNR_FIRST_ANTE; ante <= lastAnte; ante++) {
        if (wnr_weight(ante) <= 0) return ante - 1;
    }
    return lastAnte;
}

// True if any of the first n spectral creations of src in ante is Wraith.
inline bool wnr_wraith_in_triggers(instance* inst, rsrc src, int ante, int n) {
    for (int t = 0; t < n; t++) {
        if (next_spectral(inst, src, ante, false) == Wraith) return true;
    }
    return false;
}

long filter(instance* inst) {
    long score = 0;
    int lastAnte = wnr_effective_last_ante(WNR_LAST_ANTE);

    for (int ante = WNR_FIRST_ANTE; ante <= lastAnte; ante++) {
        // Every node reachable here is ante-keyed, so the previous ante's
        // slots are unreachable; discarding them keeps rng_node_resolve's
        // linear scan to the few nodes that are live (see early_negative_rares).
        inst->rngCache.nextFreeNode = 0;
        inst->rngCache.lastNode = -1;

        bool wraithReachable = wnr_wraith_in_triggers(inst, S_Sixth_Sense, ante, WNR_TRIGGERS)
                             || wnr_wraith_in_triggers(inst, S_Seance, ante, WNR_TRIGGERS);
        if (!wraithReachable) continue;

        int weight = wnr_weight(ante);

        for (int d = 0; d < WNR_WRAITH_DEPTH; d++) {
            item edition = next_joker_edition(inst, S_Wraith, ante);
#ifdef WNR_COUNT_ONLY
            if (edition == Negative) score += 1;
#else
            if (edition == Negative) score += weight;
#endif
        }
    }

    return score;
}
